import { CHIP_PROPS } from "@databiosphere/findable-ui/lib/styles/common/mui/chip";
import { ChipProps } from "@mui/material";
import { FILE_VALIDATION_STATUS } from "../../../../../../apis/catalog/hca-atlas-tracker/common/entities";
import { CAP_INGEST_STATUS } from "./entities";

export const CAP_INGEST_STATUS_COLOR: Record<
  CAP_INGEST_STATUS,
  ChipProps["color"]
> = {
  NOT_REQUIRED: CHIP_PROPS.COLOR.INFO,
  [FILE_VALIDATION_STATUS.COMPLETED]: CHIP_PROPS.COLOR.SUCCESS,
  [FILE_VALIDATION_STATUS.JOB_FAILED]: CHIP_PROPS.COLOR.ERROR,
  [FILE_VALIDATION_STATUS.PENDING]: CHIP_PROPS.COLOR.INFO,
  [FILE_VALIDATION_STATUS.REQUESTED]: CHIP_PROPS.COLOR.WARNING,
  [FILE_VALIDATION_STATUS.REQUEST_FAILED]: CHIP_PROPS.COLOR.ERROR,
  [FILE_VALIDATION_STATUS.STALE]: CHIP_PROPS.COLOR.WARNING,
};

export const CAP_INGEST_STATUS_LABEL: Record<CAP_INGEST_STATUS, string> = {
  NOT_REQUIRED: "Not Required",
  [FILE_VALIDATION_STATUS.COMPLETED]: "CAP Ready",
  [FILE_VALIDATION_STATUS.JOB_FAILED]: "Updates Required",
  [FILE_VALIDATION_STATUS.PENDING]: "Needs Validation",
  [FILE_VALIDATION_STATUS.REQUESTED]: "Needs Validation",
  [FILE_VALIDATION_STATUS.REQUEST_FAILED]: "Updates Required",
  [FILE_VALIDATION_STATUS.STALE]: "Stale",
};
