import { RowData } from "@tanstack/react-table";

export const METADATA_CORRECTNESS: RowData[] = [
  {
    name: "dataset",
    title: "Datasets",
    sourceStudies: [
      {
        sourceStudy: "BasuHelmsley",
        attributes: {
          study_pi: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Study PI",
            value: 0.125,
          },
          batch_condition: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Batch Condition",
            value: 0,
          },
          default_embedding: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Default Embedding",
            value: 0.25,
          },
          sequencing_platform: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sequencing Platform",
            value: 1,
          },
          assay_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Assay Ontology Term ID",
            value: 1,
          },
          reference_genome: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Reference Genome",
            value: 0.5,
          },
          alignment_software: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Alignment Software",
            value: 0.5,
          },
          intron_inclusion: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Intron Inclusion",
            value: 1,
          },
          sequenced_fragment: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sequenced Fragment",
            value: 1,
          },
          gene_annotation_version: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Gene Annotation Version",
            value: 1,
          },
          comments: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Comments",
            value: 1,
          },
          protocol_url: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Protocol URL",
            value: 1,
          },
          title: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Title",
            value: 1,
          },
          ambient_count_correction: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Ambient Count Correction",
            value: 1,
          },
          doublet_detection: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Doublet Detection",
            value: 1,
          },
          "X_{suffix}": {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Embedding",
            value: 1,
          },
        },
      },
      {
        sourceStudy: "Boland2020",
        attributes: {
          study_pi: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Study PI",
            value: 0.125,
          },
          batch_condition: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Batch Condition",
            value: 0,
          },
          default_embedding: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Default Embedding",
            value: 0.25,
          },
          sequencing_platform: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sequencing Platform",
            value: 1,
          },
          assay_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Assay Ontology Term ID",
            value: 1,
          },
          reference_genome: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Reference Genome",
            value: 0.5,
          },
          alignment_software: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Alignment Software",
            value: 0.5,
          },
          intron_inclusion: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Intron Inclusion",
            value: 1,
          },
          sequenced_fragment: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sequenced Fragment",
            value: 1,
          },
          gene_annotation_version: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Gene Annotation Version",
            value: 1,
          },
          comments: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Comments",
            value: 1,
          },
          protocol_url: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Protocol URL",
            value: 1,
          },
          title: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Title",
            value: 1,
          },
          ambient_count_correction: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Ambient Count Correction",
            value: 1,
          },
          doublet_detection: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Doublet Detection",
            value: 1,
          },
          "X_{suffix}": {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Embedding",
            value: 1,
          },
        },
      },
    ],
  },
  {
    name: "donors",
    title: "Donors",
    sourceStudies: [
      {
        sourceStudy: "BasuHelmsley",
        attributes: {
          donor_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Donor ID",
            value: 0.125,
          },
          organism_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Organism",
            value: 0,
          },
          manner_of_death: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Manner of Death",
            value: 0.25,
          },
          sex_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sex",
            value: 1,
          },
          self_reported_ethnicity_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Self-reported Ethnicity",
            value: 1,
          },
        },
      },
      {
        sourceStudy: "Boland2020",
        attributes: {
          donor_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Donor ID",
            value: 0.125,
          },
          organism_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Organism",
            value: 0,
          },
          manner_of_death: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Manner of Death",
            value: 0.25,
          },
          sex_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sex",
            value: 1,
          },
          self_reported_ethnicity_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Self-reported Ethnicity",
            value: 1,
          },
        },
      },
    ],
  },
  {
    name: "sample",
    sourceStudies: [
      {
        sourceStudy: "Boland2020",
        attributes: {
          sample_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sample ID",
            value: 0,
          },
          tissue_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Tissue Ontology Term ID",
            value: 0,
          },
          tissue_free_text: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Tissue Free Text",
            value: 0,
          },
          sample_source: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sample Source",
            value: 0,
          },
          sample_collection_method: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sample Collection Method",
            value: 0,
          },
          tissue_type: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Tissue Type",
            value: 0,
          },
          sampled_site_condition: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sampled Site Condition",
            value: 0,
          },
          disease_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Disease Ontology Term ID",
            value: 0,
          },
          sample_preservation_method: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Sample Preservation Method",
            value: 0,
          },
          suspension_type: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Suspension Type",
            value: 0,
          },
          is_primary_data: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Is Primary Data",
            value: 0,
          },
          development_stage_ontology_term_id: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Development Stage Ontology Term ID",
            value: 0,
          },
          radial_tissue_term: {
            bioNetworks: ["Gut"],
            required: true,
            title: "Radial Tissue Term",
            value: 0,
          },
          cell_enrichment: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Cell Enrichment",
            value: 0,
          },
          sample_collection_year: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sample Collection Year",
            value: 0,
          },
          sample_collection_site: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sample Collection Site",
            value: 0,
          },
          sample_collection_relative_time_point: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Sample Collection Relative Time Point",
            value: 0,
          },
          cell_number_loaded: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Cell Number Loaded",
            value: 0,
          },
          cell_viability_percentage: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Cell Viability Percentage",
            value: 0,
          },
          institute: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: true,
            title: "Institute",
            value: 0,
          },
          author_batch_notes: {
            bioNetworks: [
              "Adipose",
              "Breast",
              "Development",
              "Eye",
              "Genetic Diversity",
              "Gut",
              "Heart",
              "Immune",
              "Kidney",
              "Liver",
              "Lung",
              "Musculoskeletal",
              "Nervous System",
              "Oral and Craniofacial",
              "Organoid",
              "Pancreas",
              "Reproduction",
              "Skin",
            ],
            required: false,
            title: "Author Batch Notes",
            value: 0,
          },
        },
      },
    ],
    title: "Sample",
  },
];
