export enum API {
  ACTIVE_USER = "/api/me",
  ATLAS = "/api/atlases/[atlasId]",
  ATLAS_COMPONENT_ATLAS = "/api/atlases/[atlasId]/component-atlases/[componentAtlasId]",
  ATLAS_COMPONENT_ATLAS_SOURCE_DATASETS = "/api/atlases/[atlasId]/component-atlases/[componentAtlasId]/source-datasets",
  ATLAS_COMPONENT_ATLASES = "/api/atlases/[atlasId]/component-atlases",
  ATLAS_ENTRY_SHEET = "/api/atlases/[atlasId]/entry-sheet-validations/[entrySheetValidationId]",
  ATLAS_ENTRY_SHEETS = "/api/atlases/[atlasId]/entry-sheet-validations",
  ATLAS_ENTRY_SHEETS_SYNC = "/api/atlases/[atlasId]/entry-sheet-validations/sync",
  ATLAS_SOURCE_DATASET = "/api/atlases/[atlasId]/source-datasets/[sourceDatasetId]",
  ATLAS_SOURCE_DATASETS = "/api/atlases/[atlasId]/source-datasets",
  ATLAS_SOURCE_STUDIES = "/api/atlases/[atlasId]/source-studies",
  ATLAS_SOURCE_STUDY = "/api/atlases/[atlasId]/source-studies/[sourceStudyId]",
  ATLAS_SOURCE_STUDY_SOURCE_DATASET = "/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/[sourceDatasetId]",
  ATLAS_SOURCE_STUDY_SOURCE_DATASETS = "/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets",
  ATLASES = "/api/atlases",
  CREATE_ATLAS = "/api/atlases/create",
  CREATE_ATLAS_COMPONENT_ATLAS = "/api/atlases/[atlasId]/component-atlases/create",
  CREATE_ATLAS_SOURCE_STUDY = "/api/atlases/[atlasId]/source-studies/create",
  CREATE_SOURCE_DATASET = "/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/create",
  CREATE_USER = "/api/users/create",
  TASKS_COMPLETION_DATES = "/api/tasks/completion-dates",
  USER = "/api/users/[userId]",
}
