export const ROUTE = {
  ACCOUNT_DISABLED: "/account-disabled",
  ATLAS: "/atlases/[atlasId]",
  ATLASES: "/atlases",
  COMPONENT_ATLAS: "/atlases/[atlasId]/component-atlases/[componentAtlasId]",
  COMPONENT_ATLASES: "/atlases/[atlasId]/component-atlases",
  CREATE_ATLAS: "/atlases/create",
  CREATE_COMPONENT_ATLAS: "/atlases/[atlasId]/component-atlases/create",
  CREATE_SOURCE_STUDY: "/atlases/[atlasId]/source-studies/create",
  CREATE_USER: "/team/create",
  LOGIN: "/login",
  REGISTRATION_REQUIRED: "/registration-required",
  REPORTS: "/reports",
  REQUESTING_ACCESS: "/requesting-access",
  SOURCE_DATASETS:
    "/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets",
  SOURCE_STUDIES: "/atlases/[atlasId]/source-studies",
  SOURCE_STUDY: "/atlases/[atlasId]/source-studies/[sourceStudyId]",
  USER: "/team/[userId]",
  USERS: "/team",
} as const;
