export const ROUTE = {
  ATLAS: "/atlases/[atlasId]",
  ATLASES: "/atlases",
  CREATE_ATLAS: "/atlases/create",
  CREATE_SOURCE_DATASET: "/atlases/[atlasId]/source-studies/create",
  LOGIN: "/login",
  OVERVIEW: "/overview",
  REGISTRATION_REQUIRED: "/registration-required",
  REQUESTING_ACCESS: "/requesting-access",
  ROADMAP: "/roadmap",
  SOURCE_DATASET: "/atlases/[atlasId]/source-studies/[sourceStudyId]",
  SOURCE_DATASETS: "/atlases/[atlasId]/source-studies",
  TASKS: "/tasks",
  VALIDATIONS_AND_TASKS: "/validations-and-tasks",
} as const;
