export const ROUTE = {
  ATLAS: "/atlases/[atlasId]",
  ATLASES: "/atlases",
  COMPONENT_ATLAS: "/atlases/[atlasId]/component-atlases/[componentAtlasId]",
  COMPONENT_ATLASES: "/atlases/[atlasId]/component-atlases",
  CREATE_ATLAS: "/atlases/create",
  CREATE_COMPONENT_ATLAS: "/atlases/[atlasId]/component-atlases/create",
  CREATE_SOURCE_STUDY: "/atlases/[atlasId]/source-studies/create",
  LOGIN: "/login",
  OVERVIEW: "/overview",
  REGISTRATION_REQUIRED: "/registration-required",
  REPORTS: "/reports",
  REQUESTING_ACCESS: "/requesting-access",
  ROADMAP: "/roadmap",
  SOURCE_DATASETS:
    "/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets",
  SOURCE_STUDIES: "/atlases/[atlasId]/source-studies",
  SOURCE_STUDY: "/atlases/[atlasId]/source-studies/[sourceStudyId]",
  USERS: "/users",
  VALIDATIONS_AND_TASKS: "/validations-and-tasks",
} as const;
