export const GRID_TRACK_ONE = {
  MAX_WIDTH: 400,
  MIN_WIDTH: 276,
};

export const GRID_TRACK_ONE_RANGE =
  GRID_TRACK_ONE.MAX_WIDTH - GRID_TRACK_ONE.MIN_WIDTH;

export const RESPONSIVE_BREAKPOINT = {
  END: 1440,
  START: 1280,
};

export const RESPONSIVE_BREAKPOINT_RANGE =
  RESPONSIVE_BREAKPOINT.END - RESPONSIVE_BREAKPOINT.START;
