export const HCA_ATLAS_TRACKER_CATEGORY_KEY = {
  ATLAS_NAMES: "atlasNames",
  ATLAS_TITLE: "atlasTitle",
  ATLAS_VERSIONS: "atlasVersions",
  BIONETWORK: "bioNetwork",
  CELL_COUNT: "cellCount",
  COMPONENT_ATLAS_COUNT: "componentAtlasCount",
  COMPONENT_ATLAS_NAME: "componentAtlasName",
  CREATED_AT: "createdAt",
  CXG_EXPLORE_URL: "cxgExploreUrl",
  DESCRIPTION: "description",
  DISABLED: "disabled",
  DISEASE: "disease",
  DOI: "doi",
  EMAIL: "email",
  ENTITY_TITLE: "entityTitle",
  ENTITY_TYPE: "entityType",
  FULL_NAME: "fullName",
  INTEGRATION_LEAD: "integrationLeadName",
  LAST_LOGIN: "lastLogin",
  NAME: "name",
  NETWORKS: "networks",
  PROJECT_TITLE: "title",
  PUBLICATION: "publicationPubString",
  PUBLICATION_STATUS: "status",
  PUBLICATION_STRING: "publicationString",
  RELATED_ENTITY_URL: "relatedEntityUrl",
  RESOLVED_AT: "resolvedAt",
  ROLE: "role",
  ROLE_ASSOCIATED_RESOURCE_NAMES: "roleAssociatedResourceNames",
  SOURCE_STUDY_COUNT: "sourceStudyCount",
  SYSTEM: "system",
  TARGET_COMPLETION_DATE: "targetCompletion",
  TASK_STATUS: "taskStatus",
  TISSUE: "tissue",
  TITLE: "title",
  VALIDATION_TYPE: "validationType",
  VERSION: "version",
  WAVE: "wave",
  WAVES: "waves",
};

export const HCA_ATLAS_TRACKER_CATEGORY_LABEL = {
  ATLAS_NAMES: "Atlas",
  ATLAS_TITLE: "Atlas",
  ATLAS_VERSIONS: "Atlas Version",
  BIONETWORK: "Biological Network",
  CELL_COUNT: "Cells",
  COMPONENT_ATLAS_COUNT: "Integration Objects",
  COMPONENT_ATLAS_NAME: "Integration Object",
  CREATED_AT: "Created At",
  CXG_EXPLORE_URL: "Explore",
  DESCRIPTION: "Task",
  DISABLED: "Disabled",
  DISEASE: "Disease",
  DOI: "DOI",
  EMAIL: "Email",
  ENTITY_TITLE: "Title",
  ENTITY_TYPE: "Entity Type",
  FULL_NAME: "Name",
  INTEGRATION_LEAD: "Integration Lead",
  LAST_LOGIN: "Last Login",
  NAME: "Atlas",
  NETWORKS: "Network",
  PROJECT_TITLE: "Project Title",
  PUBLICATION: "Publication",
  PUBLICATION_STATUS: "Status",
  PUBLICATION_STRING: "Source Study",
  RELATED_ENTITY_URL: "Resource",
  RESOLVED_AT: "Completed At",
  ROLE: "Role",
  ROLE_ASSOCIATED_RESOURCE_NAMES: "Associated Resources",
  SOURCE_STUDY_COUNT: "Source Studies",
  SYSTEM: "System",
  TARGET_COMPLETION_DATE: "Target Completion",
  TASK_COUNTS: "Tasks",
  TASK_STATUS: "Status",
  TISSUE: "Tissue",
  TITLE: "Title",
  VALIDATION_TYPE: "Task Type",
  VERSION: "Atlas Version",
  WAVE: "Wave",
  WAVES: "Wave",
};
