export const HCA_ATLAS_TRACKER_CATEGORY_KEY = {
  ATLAS_SHORT_NAMES: "atlasShortNames",
  ATLAS_TITLE: "atlasTitle",
  BIONETWORK: "bioNetwork",
  CELL_COUNT: "cellCount",
  COMPONENT_ATLAS_NAME: "componentAtlasName",
  CXG_EXPLORE_URL: "cxgExploreUrl",
  DESCRIPTION: "description",
  DISEASE: "disease",
  ENTITY_TITLE: "entityTitle",
  ENTITY_TYPE: "entityType",
  INTEGRATION_LEAD: "integrationLeadName",
  NAME: "name",
  NETWORKS: "networks",
  PROJECT_TITLE: "title",
  PUBLICATION: "publicationPubString",
  PUBLICATION_STATUS: "status",
  PUBLICATION_STRING: "publicationString",
  SYSTEM: "system",
  TARGET_COMPLETION_DATE: "targetCompletionDate",
  TASK_STATUS: "taskStatus",
  TISSUE: "tissue",
  TITLE: "title",
  VALIDATION_TYPE: "validationType",
  VERSION: "version",
  WAVE: "wave",
  WAVES: "waves",
};

export const HCA_ATLAS_TRACKER_CATEGORY_LABEL = {
  ATLAS_SHORT_NAMES: "Atlas",
  ATLAS_TITLE: "Atlas",
  BIONETWORK: "Biological Network",
  CELL_COUNT: "Cells",
  COMPONENT_ATLAS_NAME: "Component Atlas",
  CXG_EXPLORE_URL: "Explore",
  DESCRIPTION: "Task",
  DISEASE: "Disease",
  ENTITY_TITLE: "Entity Title",
  ENTITY_TYPE: "Entity Type",
  INTEGRATION_LEAD: "Integration Lead",
  NAME: "Name",
  NETWORKS: "Biological Network",
  PROJECT_TITLE: "Project Title",
  PUBLICATION: "Publication",
  PUBLICATION_STATUS: "Status",
  PUBLICATION_STRING: "Publication",
  SYSTEM: "System",
  TARGET_COMPLETION_DATE: "Target Completion",
  TASK_STATUS: "Status",
  TISSUE: "Tissue",
  TITLE: "Atlas",
  VALIDATION_TYPE: "Task Type",
  VERSION: "Atlas Version",
  WAVE: "Wave",
  WAVES: "Wave",
};
