export const HCA_ATLAS_TRACKER_CATEGORY_KEY = {
  ASSAY: "assay",
  ATLAS_NAMES: "atlasNames",
  ATLAS_TITLE: "atlasTitle",
  ATLAS_VERSIONS: "atlasVersions",
  BIONETWORK: "bioNetwork",
  CAP_INGEST_STATUS: "capIngestStatus",
  CELL_COUNT: "cellCount",
  COMPONENT_ATLAS_COUNT: "componentAtlasCount",
  COMPONENT_ATLAS_NAME: "componentAtlasName",
  CREATED_AT: "createdAt",
  CXG_EXPLORE_URL: "cxgExploreUrl",
  DESCRIPTION: "description",
  DISABLED: "disabled",
  DISEASE: "disease",
  DOI: "doi",
  EMAIL: "email",
  ENDORSEMENT_STATUS: "status",
  ENTITY_TITLE: "entityTitle",
  ENTITY_TYPE: "entityType",
  FILE_NAME: "baseFileName",
  FULL_NAME: "fullName",
  HCA_DATA_REPOSITORY: "hcaDataRepository",
  INGESTION_COUNTS_CAP: "ingestionCountsCap",
  INTEGRATION_LEAD: "integrationLeadName",
  JOURNAL: "journal",
  LAST_LOGIN: "lastLogin",
  METADATA_SPECIFICATION_URL: "metadataSpecificationUrl",
  NAME: "name",
  NETWORKS: "networks",
  PROJECT_TITLE: "title",
  PUBLICATION: "publicationPubString",
  PUBLICATION_STATUS: "publicationStatus",
  PUBLICATION_STRING: "publicationString",
  PUBLISHED_AT: "publishedAt",
  RELATED_ENTITY_URL: "relatedEntityUrl",
  RESOLVED_AT: "resolvedAt",
  ROLE: "role",
  ROLE_ASSOCIATED_RESOURCE_NAMES: "roleAssociatedResourceNames",
  SOURCE_DATASET_COUNT: "sourceDatasetCount",
  SOURCE_STUDY_COUNT: "sourceStudyCount",
  SUSPENSION_TYPE: "suspensionType",
  SYSTEM: "system",
  TARGET_COMPLETION_DATE: "targetCompletion",
  TASK_STATUS: "taskStatus",
  TIER1_VALIDATION_STATUS: "hcaTier1ValidationStatus",
  TISSUE: "tissue",
  TITLE: "title",
  UPDATED_AT: "updatedAt",
  VALIDATION_STATUS: "validationStatus",
  VALIDATION_TYPE: "validationType",
  VERSION: "version",
  WAVES: "waves",
};

export const HCA_ATLAS_TRACKER_CATEGORY_LABEL = {
  ASSAY: "Assay",
  ATLAS_NAMES: "Atlas",
  ATLAS_TITLE: "Atlas",
  ATLAS_VERSIONS: "Atlas Version",
  BIONETWORK: "Biological Network",
  CAP_INGEST_STATUS: "CAP Ingest Status",
  CELL_COUNT: "Cells",
  COMPONENT_ATLAS_COUNT: "Integrated Objects",
  COMPONENT_ATLAS_NAME: "Integrated Object",
  CREATED_AT: "Created At",
  CXG_EXPLORE_URL: "Explore",
  DESCRIPTION: "Task",
  DISABLED: "Disabled",
  DISEASE: "Disease",
  DOI: "DOI",
  EMAIL: "Email",
  ENDORSEMENT_STATUS: "OC Endorsed",
  ENTITY_TITLE: "Title",
  ENTITY_TYPE: "Entity Type",
  FILE_NAME: "File Name",
  FULL_NAME: "Name",
  HCA_DATA_REPOSITORY: "HCA Data Repository",
  INGESTION_COUNTS_CAP: "CAP Projects",
  INGESTION_COUNTS_CELLXGENE: "CELLxGENE Collections",
  INGESTION_COUNTS_HCA: "HCA Data Repository Projects Ingested",
  INTEGRATION_LEAD: "Integration Lead",
  JOURNAL: "Journal",
  LAST_LOGIN: "Last Login",
  METADATA_SPECIFICATION_URL: "Metadata Spec (Golden Sheet)",
  METADATA_SPREADSHEETS: "Metadata Entry Sheet",
  NAME: "Atlas",
  NETWORKS: "Network",
  PROJECT_TITLE: "Project Title",
  PUBLICATION: "Publication",
  PUBLICATION_STATUS: "Publication Status",
  PUBLICATION_STRING: "Source Study",
  PUBLISHED_AT: "Release Date",
  RELATED_ENTITY_URL: "Resource",
  RESOLVED_AT: "Completed At",
  ROLE: "Role",
  ROLE_ASSOCIATED_RESOURCE_NAMES: "Associated Resources",
  SOURCE_DATASET_COUNT: "Source Datasets",
  SOURCE_STUDY_COUNT: "Source Studies",
  SUSPENSION_TYPE: "Suspension Type",
  SYSTEM: "System",
  TARGET_COMPLETION_DATE: "Target Completion",
  TASK_STATUS: "Status",
  TIER1_VALIDATION_STATUS: "HCA Tier-1 Status",
  TISSUE: "Tissue",
  TITLE: "Title",
  UPDATED_AT: "Updated At",
  VALIDATION_STATUS: "Validation Status",
  VALIDATION_TYPE: "Task Type",
  VERSION: "Atlas Version",
  WAVES: "Wave",
};
