export const FIELD_NAME = {
  CAP_INGEST_STATUS: "capIngestStatus",
  CAP_URL: "capUrl",
  CELL_COUNT: "cellCount",
  DOWNLOAD_NAME: "downloadName",
  FILE_EVENT_TIME: "fileEventTime",
  FILE_NAME: "baseFileName",
  GENE_COUNT: "geneCount",
  PUBLICATION_STATUS: "publicationStatus",
  PUBLISHED_AT: "publishedAt",
  SIZE_BYTES: "sizeBytes",
  TITLE: "title",
  VALIDATION_STATUS: "validationStatus",
  VERSION: "version",
} as const;
