import { ROUTE } from "../../../routes/constants";
import { RouteValue } from "../../../routes/entities";

export const ROUTES: RouteValue[] = [
  ROUTE.ATLAS_SOURCE_DATASET,
  ROUTE.ATLAS_SOURCE_DATASETS,
  ROUTE.COMPONENT_ATLAS,
  ROUTE.COMPONENT_ATLASES,
  ROUTE.CREATE_SOURCE_STUDY,
  ROUTE.INTEGRATED_OBJECT_SOURCE_DATASETS,
  ROUTE.SOURCE_DATASETS,
  ROUTE.SOURCE_STUDIES,
  ROUTE.SOURCE_STUDY,
];
