import { ROUTE } from "@/app/routes/constants";
import { RouteValue } from "@/app/routes/entities";

export const ROUTES: RouteValue[] = [
  ROUTE.ATLAS_SOURCE_DATASETS,
  ROUTE.ATLAS_SOURCE_STUDIES,
  ROUTE.ATLAS_SOURCE_STUDY,
  ROUTE.ATLAS_SOURCE_STUDY_SOURCE_DATASETS,
  ROUTE.COMPONENT_ATLASES,
  ROUTE.CREATE_SOURCE_STUDY,
  ROUTE.INTEGRATED_OBJECT_SOURCE_DATASETS,
];
